application: xiaogaozi
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets

- url: /project
  static_files: project.html
  upload: project.html

- url: /about
  static_files: about.html
  upload: about.html

- url: /.*
  static_files: index.html
  upload: index.html
